[window_mode]
# 16:9 ratio
width = 1280
height = 720
borderless = false
fullscreen_type = "Off"
vsync = true
min_width = 0
max_width = 0
min_height = 0
max_height = 0

[window_setup]
title = "My First Roguelike"
icon = ""
resizable = false
allow_highdpi = true
samples = "One"

[backend]
type = "OpenGL"
major = 3
minor = 2