[package]
name = "rust-rl"
version = "0.1.0"
authors = ["Jason Olson <jolson88@outlook.com>"]

[dependencies]
env_logger = "0.5.13"
log = "0.4.0"
rand = "0.3.9"

[dependencies.ggez]
version = "0.4"
features = ["cargo-resource-root"]